config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/tasks", to: 'tasks#index'

  get "/tasks/new", to: 'tasks#new'
  post "/tasks", to: 'tasks#create'

  get "/tasks/:id/edit", to: 'tasks#edit', as: :task_edit

  get "/tasks/:id", to: 'tasks#show', as: :task
  patch "/tasks/:id", to: 'tasks#update'

  delete "/tasks/:id", to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/51e1921127.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit <%= @task.title %></h1>
<%# <%= render 'form', task: @task %>
<%= form_for @task do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.text_field :completed %>

  <%= f.submit %>

<%end%>

app/views/tasks/index.html.erb
<h1>All tasks</h1>
<ul>
  <% @tasks.each do |task| %>
  <li>
  <%= link_to task.title, task_path(task.id) %>
 <%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
<i class="far fa-trash-alt"></i>
<% end %>
  </li>
  <% end %>
</ul>

<%= link_to "Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>
<%= form_for Task.new do |f|%>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>

<%end%>

app/views/tasks/show.html.erb
<h1><%= @task.title%></h1>
<ul>
<li><%= @task.details%></li>
<li><%= @task.completed%></li>
</ul>
<%= link_to "Back to list", tasks_path %>
<%= link_to "Edit task", task_edit_path %>

<%= link_to "Delete #{@task.title}",
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>